"""RunOne 工具目录（自动生成 —— 勿手改）。

数据来自 RunOne 服务端 `/mcp` 的 `tools/list`——也就是 MCP 客户端今天看到的同一份
schema：字段名、必填项与中文描述与线上实现逐字一致。要更新就重跑：

    python scripts/gen_catalog.py            # 打生产 /mcp，覆盖本文件

生成而不手写，是为了不让「插件声明的工具」与「服务端实现」两处漂移。
"""

from __future__ import annotations

TOOLS = [{'name': 'list_today_tasks',
  'description': '列出今天到期或逾期的未完成任务（今日视图）。若要安排某个任务「在今天」，请在创建时把 dueDate 或 nextRunDate '
                 '设为今天（YYYY-MM-DD），也可以带时间（YYYY-MM-DDTHH:mm）表示当天的具体时刻。',
  'parameters': {'type': 'object'}},
 {'name': 'list_projects',
  'description': '列出所有项目，返回项目名称、id 与**你的**工作目录（本地磁盘路径，若有）。工作目录按「项目 × '
                 '成员」存：有你自己那行就用你的，没填过回退项目级默认；用于把新任务归类到某个项目，以及确定处理该项目任务时的工作目录。',
  'parameters': {'type': 'object'}},
 {'name': 'list_assigned_tasks',
  'description': '列出分配给「AI 助手」的任务（即需要由 AI '
                 '承接的工作），默认不含已完成/已关闭；可选按状态（todo/doing/closed/done/assigning/testing）或项目名称过滤。每个任务附带所在项目与**你的**工作目录（按「项目 '
                 '× 成员」存，没填过回退项目级；与 list_projects 一致）。AI 助手成员可以有多条（如「AI 助手-研发」「AI '
                 '助手-文案」），本工具只回**绑定到你账号的那一条**的活；一条都没绑定时回退成「你能看到的全部 AI 助手成员」。',
  'parameters': {'type': 'object',
                 'properties': {'status': {'type': 'string',
                                           'enum': ['todo', 'doing', 'closed', 'done', 'assigning', 'testing']},
                                'project_name': {'type': 'string'},
                                'include_terminal': {'description': '是否包含已完成/已关闭', 'type': 'boolean'}}}},
 {'name': 'take_task',
  'description': '承接任务：把任务置为「进行中」（doing）。任务 id 来自 list_assigned_tasks / find_tasks。开始动手前先调用本工具，让任务状态与实际情况一致。',
  'parameters': {'type': 'object', 'properties': {'task_id': {'type': 'string'}}, 'required': ['task_id']}},
 {'name': 'submit_task_result',
  'description': '提交任务结果：写入一条 AI 回复的任务进度（摘要），并把任务状态置为「待测试」（testing）等待用户验收。只在任务实际完成后调用，即「完成并提交交付」。',
  'parameters': {'type': 'object',
                 'properties': {'task_id': {'type': 'string'},
                                'summary': {'type': 'string',
                                            'minLength': 1,
                                            'maxLength': 2000,
                                            'description': '完成摘要：做了什么、产出物、如何验证，1~2000 字'}},
                 'required': ['task_id', 'summary']}},
 {'name': 'find_tasks',
  'description': '按标题关键词搜索任务，可选按状态（todo/doing/closed/done/assigning/testing）或项目名称过滤。用于先定位再操作。',
  'parameters': {'type': 'object',
                 'properties': {'query': {'type': 'string', 'minLength': 1},
                                'status': {'type': 'string',
                                           'enum': ['todo', 'doing', 'closed', 'done', 'assigning', 'testing']},
                                'project_name': {'type': 'string'}},
                 'required': ['query']}},
 {'name': 'create_task',
  'description': '新增任务。title 必填；project_name 可选（归到某项目，缺省为未分类/收件箱）。若要安排到具体某天，设置 '
                 'dueDate/startDate/nextRunDate（YYYY-MM-DD），需要精确到分钟时写成 YYYY-MM-DDTHH:mm（本地时间）；nextRunDate 或 dueDate '
                 '决定它是否出现在「今天」视图。',
  'parameters': {'type': 'object',
                 'properties': {'title': {'type': 'string', 'minLength': 1, 'maxLength': 500},
                                'project_name': {'type': 'string'},
                                'dueDate': {'type': 'string',
                                            'pattern': '^\\d{4}-\\d{2}-\\d{2}(T([01]\\d|2[0-3]):[0-5]\\d)?$'},
                                'startDate': {'type': 'string',
                                              'pattern': '^\\d{4}-\\d{2}-\\d{2}(T([01]\\d|2[0-3]):[0-5]\\d)?$'},
                                'nextRunDate': {'type': 'string',
                                                'pattern': '^\\d{4}-\\d{2}-\\d{2}(T([01]\\d|2[0-3]):[0-5]\\d)?$'},
                                'priority': {'type': 'string', 'enum': ['none', 'low', 'medium', 'high']},
                                'notes': {'type': 'string'},
                                'estimatedMinutes': {'type': 'integer', 'minimum': 1, 'maximum': 525600}},
                 'required': ['title']}},
 {'name': 'complete_task',
  'description': '完成任务：传入 task_id（优先），或提供 title 精确匹配（可加 project_name 消歧）。完成后任务会从未完成列表移除，并出现在「已完成」视图。注意：给 AI 的活儿请用 '
                 'submit_task_result 提交并进入「待测试」流程。',
  'parameters': {'type': 'object',
                 'properties': {'task_id': {'type': 'string'},
                                'title': {'type': 'string'},
                                'project_name': {'type': 'string'}}}},
 {'name': 'update_task',
  'description': '更新任务字段：task_id 必填，可改 title / dueDate / startDate / nextRunDate / priority / '
                 'status（todo/doing/closed/done/assigning/testing）/ project_name / notes / '
                 'estimatedMinutes。日期可精确到分钟（YYYY-MM-DDTHH:mm，本地时间）。只传需要改的字段。',
  'parameters': {'type': 'object',
                 'properties': {'task_id': {'type': 'string'},
                                'title': {'type': 'string', 'minLength': 1, 'maxLength': 500},
                                'dueDate': {'anyOf': [{'type': 'string',
                                                       'pattern': '^\\d{4}-\\d{2}-\\d{2}(T([01]\\d|2[0-3]):[0-5]\\d)?$'},
                                                      {'type': 'null'}]},
                                'startDate': {'anyOf': [{'type': 'string',
                                                         'pattern': '^\\d{4}-\\d{2}-\\d{2}(T([01]\\d|2[0-3]):[0-5]\\d)?$'},
                                                        {'type': 'null'}]},
                                'nextRunDate': {'anyOf': [{'type': 'string',
                                                           'pattern': '^\\d{4}-\\d{2}-\\d{2}(T([01]\\d|2[0-3]):[0-5]\\d)?$'},
                                                          {'type': 'null'}]},
                                'priority': {'type': 'string', 'enum': ['none', 'low', 'medium', 'high']},
                                'status': {'type': 'string',
                                           'enum': ['todo', 'doing', 'closed', 'done', 'assigning', 'testing']},
                                'project_name': {'type': 'string'},
                                'notes': {'type': ['string', 'null']},
                                'estimatedMinutes': {'anyOf': [{'type': 'integer', 'minimum': 1, 'maximum': 525600},
                                                               {'type': 'null'}]}},
                 'required': ['task_id']}},
 {'name': 'create_goal',
  'description': '新增目标。目标是与任务并列的独立对象（任务是它下面的行动），有自己的进度与生命周期（not_started/active/achieved/abandoned/paused）。title '
                 '必填；归属：给了 project_name 就自动落到该项目所在空间，否则必须给 space_name（工作/个人/副业）；parent_title 可建子目标（继承父目标的空间）。进度口径 '
                 'progress_mode：rollup=按关联任务汇总（建任务后记得用 link_task_to_goal 挂上去）/ numeric=数值指标（配 target_value 与 '
                 'unit，如回款 60 万元）/ count=周期内计数（如每周 3 次）/ manual=手填百分比 / none=不跟踪。周期：给 '
                 'period_preset（year/quarter/month/week）会按今天所处周期自动填起止，也可以直接给 start_date 与 '
                 'due_date（YYYY-MM-DD）做自定义周期。',
  'parameters': {'type': 'object',
                 'properties': {'title': {'type': 'string', 'minLength': 1, 'maxLength': 200},
                                'space_name': {'description': '空间名：工作 / 个人 / 副业（给了 project_name 时可不填）',
                                               'type': 'string'},
                                'project_name': {'type': 'string'},
                                'parent_title': {'description': '父目标标题（建子目标）', 'type': 'string'},
                                'progress_mode': {'type': 'string',
                                                  'enum': ['rollup', 'numeric', 'count', 'manual', 'none']},
                                'unit': {'description': '指标单位，如 万元 / 本 / 次', 'type': 'string', 'maxLength': 20},
                                'target_value': {'description': '目标值（numeric / count 用）', 'type': 'number'},
                                'current_value': {'description': '当前值（numeric 用；manual 时是百分比 0~100）',
                                                  'type': 'number'},
                                'start_date': {'type': 'string', 'pattern': '^\\d{4}-\\d{2}-\\d{2}$'},
                                'due_date': {'type': 'string', 'pattern': '^\\d{4}-\\d{2}-\\d{2}$'},
                                'period_preset': {'description': '周期预设；只给它会按今天所处周期自动填起止',
                                                  'type': 'string',
                                                  'enum': ['year', 'quarter', 'month', 'week']},
                                'owner_name': {'description': '负责人（成员名，如 我）', 'type': 'string'},
                                'owner_member_id': {'description': '负责人（成员 id）：有同名成员时用它精确指定，优先级高于 owner_name',
                                                    'type': 'string'},
                                'status': {'type': 'string',
                                           'enum': ['not_started', 'active', 'achieved', 'abandoned', 'paused']},
                                'notes': {'description': '描述 / 验收标准', 'type': 'string'},
                                'metric_name': {'description': '挂到某个指标（按名字，如 俯卧撑数量）：挂上后进度由该指标的记录推导，不要再手填 '
                                                               'current_value',
                                                'type': 'string'}},
                 'required': ['title']}},
 {'name': 'list_goals',
  'description': '列出目标（含空间、项目、状态、进度、周期、关联任务数与 id）。默认不含已达成/已放弃，可用 include_terminal=true 看全部。可按 '
                 'space_name（工作/个人/副业）、project_name、status 过滤，或用 parent_title 只看某个目标的子目标。',
  'parameters': {'type': 'object',
                 'properties': {'space_name': {'type': 'string'},
                                'project_name': {'type': 'string'},
                                'status': {'type': 'string',
                                           'enum': ['not_started', 'active', 'achieved', 'abandoned', 'paused']},
                                'include_terminal': {'type': 'boolean'},
                                'parent_title': {'description': '只看该目标的直接子目标', 'type': 'string'}}}},
 {'name': 'link_task_to_goal',
  'description': '把任务关联到目标（多对多：一条任务可同时支撑多个目标）。用 task_id 或 task_title 指定任务，用 goal_id 或 goal_title 指定目标；unlink=true '
                 '则解除关联（只解绑，不删任务）。给 rollup 口径的目标挂上任务后，目标进度就按这些任务的完成情况自动汇总。',
  'parameters': {'type': 'object',
                 'properties': {'task_id': {'type': 'string'},
                                'task_title': {'type': 'string'},
                                'project_name': {'description': '配合 task_title 消歧', 'type': 'string'},
                                'goal_id': {'type': 'string'},
                                'goal_title': {'type': 'string'},
                                'unlink': {'description': 'true = 解除关联', 'type': 'boolean'}}}},
 {'name': 'update_goal',
  'description': '更新目标：用 goal_id 或 goal_title 指定，可改 title / status（not_started/active/achieved/abandoned/paused）/ '
                 'progress_mode / current_value / target_value / unit / start_date / due_date / owner_name / '
                 'project_name / notes。数值型目标（回款 60 万元这类）就用它推进度：把 current_value 改成最新值即可。只传需要改的字段，日期传 null 清除。',
  'parameters': {'type': 'object',
                 'properties': {'goal_id': {'type': 'string'},
                                'goal_title': {'type': 'string'},
                                'title': {'type': 'string', 'minLength': 1, 'maxLength': 200},
                                'status': {'type': 'string',
                                           'enum': ['not_started', 'active', 'achieved', 'abandoned', 'paused']},
                                'progress_mode': {'type': 'string',
                                                  'enum': ['rollup', 'numeric', 'count', 'manual', 'none']},
                                'current_value': {'type': ['number', 'null']},
                                'target_value': {'type': ['number', 'null']},
                                'unit': {'anyOf': [{'type': 'string', 'maxLength': 20}, {'type': 'null'}]},
                                'start_date': {'anyOf': [{'type': 'string', 'pattern': '^\\d{4}-\\d{2}-\\d{2}$'},
                                                         {'type': 'null'}]},
                                'due_date': {'anyOf': [{'type': 'string', 'pattern': '^\\d{4}-\\d{2}-\\d{2}$'},
                                                       {'type': 'null'}]},
                                'owner_name': {'type': ['string', 'null']},
                                'owner_member_id': {'description': '负责人（成员 id）：有同名成员时用它精确指定；null 表示清空，优先级高于 '
                                                                   'owner_name',
                                                    'type': ['string', 'null']},
                                'project_name': {'description': 'null 表示解除项目挂载', 'type': ['string', 'null']},
                                'notes': {'type': ['string', 'null']},
                                'metric_name': {'description': '挂到某个指标（按名字）；null 解除挂载',
                                                'type': ['string', 'null']}}}},
 {'name': 'create_metric',
  'description': '新增指标（可测量的东西：俯卧撑数量、体重、回款）。目标挂在指标上，记录也挂在指标上；同一个指标可以建不同周期、不同目标值的目标。归属：给了 project_name '
                 '就落到该项目所在空间，否则必须给 space_name（工作/个人/副业）。聚合口径 agg：sum 求和（回款 60 万、今年读 12 本）/ latest 最新值（体重、毛利率）/ max '
                 '最大值 / min 最小值 / avg 平均值 / days 达标天数（配合 day_target，如每天 10 个俯卧撑坚持 15 天）/ records 记录条数。direction：up '
                 '越高越好（默认）/ down 越低越好（体重、成本率）。day_target 只在 days 口径下生效。',
  'parameters': {'type': 'object',
                 'properties': {'name': {'type': 'string',
                                         'minLength': 1,
                                         'maxLength': 60,
                                         'description': '指标名，如 俯卧撑数量'},
                                'space_name': {'description': '空间名：工作 / 个人 / 副业（给了 project_name 时可不填）',
                                               'type': 'string'},
                                'project_name': {'type': 'string'},
                                'unit': {'description': '单位：个 / kg / 万元', 'type': 'string', 'maxLength': 20},
                                'agg': {'type': 'string',
                                        'enum': ['sum', 'latest', 'max', 'min', 'avg', 'days', 'records']},
                                'direction': {'type': 'string', 'enum': ['up', 'down']},
                                'day_target': {'description': '每日门槛（days 口径用），如 10', 'type': 'number'}},
                 'required': ['name']}},
 {'name': 'list_metrics',
  'description': '列出指标（名称、空间、单位、聚合口径、方向、每日门槛、记录条数、id）。默认不含已停用的，include_archived=true 看全部。可按 space_name 过滤。',
  'parameters': {'type': 'object',
                 'properties': {'space_name': {'type': 'string'}, 'include_archived': {'type': 'boolean'}}}},
 {'name': 'add_metric_record',
  'description': '给指标打卡（新增一条记录，一天可以多条）。用 metric_id 或 metric_name 指定指标；date 缺省为今天（YYYY-MM-DD），value 缺省 1。可选 goal_id / '
                 'goal_title 标注「这次是为哪个目标做的」（只作标注，不影响聚合口径）。记录是进度的唯一来源：挂了这个指标的每个目标都按自己的窗口读同一批记录，所以同一天只需要记一次。',
  'parameters': {'type': 'object',
                 'properties': {'metric_id': {'type': 'string'},
                                'metric_name': {'type': 'string'},
                                'date': {'type': 'string', 'pattern': '^\\d{4}-\\d{2}-\\d{2}$'},
                                'value': {'description': '数量 / 数值（俯卧撑 10 个、体重 66.2、回款 10 万元）', 'type': 'number'},
                                'note': {'type': 'string', 'maxLength': 2000},
                                'goal_id': {'type': 'string'},
                                'goal_title': {'type': 'string'}}}},
 {'name': 'list_metric_records',
  'description': '列出某个指标的记录（按日期升序，含当天多条）。用 metric_id 或 metric_name 指定指标，可用 from/to（YYYY-MM-DD）限定区间，limit 缺省 30 '
                 '条（取最近的）。',
  'parameters': {'type': 'object',
                 'properties': {'metric_id': {'type': 'string'},
                                'metric_name': {'type': 'string'},
                                'from': {'type': 'string', 'pattern': '^\\d{4}-\\d{2}-\\d{2}$'},
                                'to': {'type': 'string', 'pattern': '^\\d{4}-\\d{2}-\\d{2}$'},
                                'limit': {'type': 'integer', 'minimum': 1, 'maximum': 200}}}},
 {'name': 'create_recurrence',
  'description': '新建重复任务模板（模型 = 模板 + 惰性材料化：按规则生成真实的实例任务，它们进今日视图、会逾期、能指派，漏做就是真的没做）。freq：daily 每天 / interval_days 每 N '
                 '天 / weekly 每周（weekdays 多选周几）/ interval_weeks 每 N 周 / monthly 每月几号（小月落在当月最后一天）/ monthly_last 每月最后一天 '
                 '/ weekdays 工作日。start_date 是第一次发生（默认今天；填过去的日子，窗口内的会补成逾期）；until 可选（含当天）；time 可到分钟（HH:mm）。可选 '
                 'metric_name + record_value：完成一条实例时自动回写一条指标记录（「每天 10 个俯卧撑」就填 record_value=10）。',
  'parameters': {'type': 'object',
                 'properties': {'title': {'type': 'string',
                                          'minLength': 1,
                                          'maxLength': 500,
                                          'description': '模板名，同时是每条实例的标题'},
                                'freq': {'type': 'string',
                                         'enum': ['daily',
                                                  'interval_days',
                                                  'weekly',
                                                  'interval_weeks',
                                                  'monthly',
                                                  'monthly_last',
                                                  'weekdays']},
                                'interval': {'description': '间隔，仅 interval_days / interval_weeks 用',
                                             'type': 'integer',
                                             'minimum': 1,
                                             'maximum': 9007199254740991},
                                'weekdays': {'description': '周几（1=周一 … 7=周日），weekly / interval_weeks 用，可多选',
                                             'type': 'array',
                                             'items': {'type': 'integer', 'minimum': 1, 'maximum': 7}},
                                'month_day': {'description': '每月几号，monthly 用',
                                              'type': 'integer',
                                              'minimum': 1,
                                              'maximum': 31},
                                'start_date': {'description': '第一次发生 YYYY-MM-DD（默认今天）', 'type': 'string'},
                                'until': {'description': '结束 YYYY-MM-DD（含当天），不填 = 一直重复', 'type': 'string'},
                                'time': {'description': '排期时刻 HH:mm（本地时间）', 'type': 'string'},
                                'project_name': {'type': 'string'},
                                'member_names': {'description': '负责人，逗号分隔（如「我,AI助手」），实例继承', 'type': 'string'},
                                'estimated_minutes': {'type': 'integer', 'minimum': 1, 'maximum': 525600},
                                'priority': {'type': 'string', 'enum': ['none', 'low', 'medium', 'high']},
                                'metric_name': {'description': '完成时回写的指标（不填 = 不回写）', 'type': 'string'},
                                'record_value': {'description': '每次完成回写的数量，默认 1', 'type': 'number'}},
                 'required': ['title', 'freq']}},
 {'name': 'list_recurrences',
  'description': '列出重复任务模板：规则文案、下一次发生日、已完成/跳过/未完成的实例数、id。默认不含已停用（include_archived=true 看全部），可按 project_name 过滤。',
  'parameters': {'type': 'object',
                 'properties': {'project_name': {'type': 'string'}, 'include_archived': {'type': 'boolean'}}}},
 {'name': 'update_recurrence',
  'description': '更新重复任务模板：用 recurrence_id（优先）或 title 精确匹配定位。可改 freq / interval / weekdays / month_day / start_date '
                 '/ until / time / project_name / member_names / estimated_minutes / priority / metric_name / '
                 'record_value。scope=series（默认）改整个系列（未来生成跟着变，历史实例不动）；scope=future + from=YYYY-MM-DD '
                 '表示「本次及以后」：模板分裂成前后两段，历史实例仍归旧规则。archived=true 停用（不再生成新实例）/ false 恢复。',
  'parameters': {'type': 'object',
                 'properties': {'recurrence_id': {'type': 'string'},
                                'title': {'description': '按标题定位（与 recurrence_id 二选一；标题需唯一）', 'type': 'string'},
                                'freq': {'type': 'string',
                                         'enum': ['daily',
                                                  'interval_days',
                                                  'weekly',
                                                  'interval_weeks',
                                                  'monthly',
                                                  'monthly_last',
                                                  'weekdays']},
                                'interval': {'type': 'integer', 'minimum': 1, 'maximum': 9007199254740991},
                                'weekdays': {'type': 'array',
                                             'items': {'type': 'integer', 'minimum': 1, 'maximum': 7}},
                                'month_day': {'anyOf': [{'type': 'integer', 'minimum': 1, 'maximum': 31},
                                                        {'type': 'null'}]},
                                'start_date': {'type': 'string'},
                                'until': {'type': ['string', 'null']},
                                'time': {'type': ['string', 'null']},
                                'project_name': {'type': 'string'},
                                'member_names': {'type': 'string'},
                                'estimated_minutes': {'anyOf': [{'type': 'integer', 'minimum': 1, 'maximum': 525600},
                                                                {'type': 'null'}]},
                                'priority': {'type': 'string', 'enum': ['none', 'low', 'medium', 'high']},
                                'metric_name': {'type': ['string', 'null']},
                                'record_value': {'type': ['number', 'null']},
                                'archived': {'type': 'boolean'},
                                'scope': {'type': 'string', 'enum': ['series', 'future']},
                                'from': {'description': 'scope=future 时的本次发生日 YYYY-MM-DD', 'type': 'string'}}}},
 {'name': 'skip_occurrence',
  'description': '跳过重复任务的某一次：把那条实例置为 closed（不删实例、不会被重新生成；想恢复用 update_task 把状态改回 todo）。用 task_id 直接指定那条实例；或用 '
                 'recurrence_title + date（默认今天）定位。',
  'parameters': {'type': 'object',
                 'properties': {'task_id': {'type': 'string'},
                                'recurrence_title': {'type': 'string'},
                                'date': {'description': '发生日 YYYY-MM-DD（默认今天）', 'type': 'string'}}}},
 {'name': 'list_my_account',
  'description': '查看当前 MCP 身份：账号的名字与邮箱、所属空间及角色；服务身份（部署者静态 token）会说明「不过滤、全权限」。用于确认「我现在以谁的身份在操作」，以及在收到「没有权限」时判断该找谁授权。',
  'parameters': {'type': 'object'}}]
